### PR TITLE
Fix issues with build

### LINKED ISSUE #79: Fix issues with build

### PR DESCRIPTION
**Pull request by Shearer1509**
Fixes #79

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 1]
```diff
@@ -11,6 +11,7 @@
 import java.nio.file.Paths;
 import java.util.ArrayList;
 import java.util.Arrays;
+import java.util.Comparator;
```
Comment (polyrhythmas) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Good choice to import the Comparator class!
